### ISSUE TITLE
how to set c++17 in bazel config file.

### ISSUE THREAD

**Issue by brioyche** [cloudhan/rules_cuda#16]
hi cloudhan,
your project help me a lot. It is a great job. I dont understand cuda compile very well. I can compile cuda code with "cuda_library" now. The question is I want to use std::any which is C++ 17 version. How can I set cuda code compile in C++17.  I install cuda11.7,  "nvcc test.cc -std=c++17 -o test"  is ok. 
Thank you.

**Comment by cloudhan** [comment]
You can use [`--@rules_cuda//cuda:copts`](https://github.com/cloudhan/rules_cuda/blob/d95437f963d501aec284e9daf22c36ad4e4651fd/.bazelrc#L5)

You can test it out in the command line with `bazel build --@rules_cuda//cuda:copts=-std=c++17`, if it works as expected, then you can add one line your `.bazelrc`:
```
build --@rules_cuda//cuda:copts=-std=c++17
```

**Comment by brioyche** [comment]
Thank you very much. The config worked.  This project should be a standard for bazel.
