### ISSUE TITLE
gtest_main not linked correctly without srcs

### ISSUE THREAD

**Issue by skyw** [cloudhan/rules_cuda#20]
with exact same content, one in cu file, one in cpp file

```c++
//a.cpp
#include <gtest/gtest.h>
#include <iostream>

TEST(Dummy, CPP) {
  std::cout << "this is in cpp file" << std::endl;
}
```

```cuda
// a.cu
#include <gtest/gtest.h>
#include <iostream>

TEST(Dummy, CU) {
  std::cout << "this is in cu file" << std::endl;
}
```

BUILD file
```bazel
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

package(default_visibility = ["//visibility:public"])

cuda_library(
    name = "a_cu",
    srcs = ["a.cu"]
)

cc_test(
    name = "dummy_test_cu",
    deps = [
        ":a_cu",
        "@com_google_googletest//:gtest_main",
    ]
 )
cc_test(
    name = "dummy_test",
    srcs = ["a.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
```

If I run
`bazel test  --test_output=all //:dummy_test`
1 test will run.
```shell
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Dummy
[ RUN      ] Dummy.CPP
this is in cpp file
[       OK ] Dummy.CPP (0 ms)
[----------] 1 test from Dummy (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```

But if I run
`bazel test --config=cuda --test_output=all //:dummy_test_cu`
Everything will build and run "successfully". except no test is actually run
```shell
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

I do need to define test as cu file because there will be CUDA code in it. Technically they can be wrapped in another lib and test file only contains pure c++ code, but that's extra work. Besides, a silent success without tests being actually run is dangerous. It can be easily missed in a bigger project.

Maybe explicitly support `cuda_test` and `cuda_binary`?

**Comment by cloudhan** [comment]
This should be fixable by adding `alwayslink=True` to your `cuda_library` which has test impl must present in final binary.

`cuda_test` and `cuda_binary` will largely share the same logic with cc rules, it is not worth the effort. At the moment, it can be implemented as macro.

**Comment by skyw** [comment]
> alwayslink=True

Adding `alwayslink=True` does the trick. Any low effort option to make it fail instead of running 0 tests?

**Comment by cloudhan** [comment]
This boils down to you own customization problem.  I think you can rollout your own version of test main and it should be quiet simple:
```cpp
int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  EXPECT_GT(::testing::UnitTest::GetInstance()->total_test_suite_count(), 0);
  return RUN_ALL_TESTS();
}
```

[ref](https://github.com/google/googletest/blob/8c4dc11539e814ad7e16f3063dd0e36c4fd5a9b4/googletest/test/googletest-param-test-test.cc#L960-L966)

**Comment by skyw** [comment]
> This boils down to you own customization problem. I think you can rollout your own version of test main and it should be quiet simple:
> 
> ```c++
> int main(int argc, char **argv) {
>   ::testing::InitGoogleTest(&argc, argv);
>   EXPECT_GT(::testing::UnitTest::GetInstance()->total_test_suite_count(), 0);
>   return RUN_ALL_TESTS();
> }
> ```
> 
> [ref](https://github.com/google/googletest/blob/8c4dc11539e814ad7e16f3063dd0e36c4fd5a9b4/googletest/test/googletest-param-test-test.cc#L960-L966)

It can work. But I think the point gtest_main target exists is not to have the same main function in every test file. And cmake links gtest_main fine with .cu file in one of my project that I maintain both bazel and cmake build.

**Comment by cloudhan** [comment]
I mean, there is nothing prevent you from add a `cc_library` named as `your_main` and link it together with your `cuda_library`s, since you want it signal you when no test is found. CMake can also suffer from this problem if you

```cmake
add_library(a_cu_lib STATIC CU_FILES)
add_executable(dummy_test_cu a_cu_lib gtest_main)
```

The problems here is the `a_cu_lib` library is static and there is no symbol is referenced in the main function. Then you will need whole archive linking. And this is what `alwayslink=True` is doing. It is not a trick or walkaround in any form, it is how it should be. If the problem still present, then it is a bug in these rules.

I'd prefer the following macro, and you should not present a `your_main`
```py
def cuda_test(name, srcs, deps, *args, *kwargs):
    cuda_library(name = name + "_cu", srcs = srcs, alwayslink=True)
    cc_test(name = name, deps = [name + "_cu"] + deps)
```
